"""add authorization time and capture id

Revision ID: 506ae7627024
Revises: 392cbde33fcd
Create Date: 2026-10-05 18:29:22.038898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506ae7627024'
down_revision: Union[str, Sequence[str], None] = '392cbde33fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('paypal_capture_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'paypal_capture_id')
    op.drop_column('orders', 'authorized_at')
    # ### end Alembic commands ###
