"""add chat messages

Revision ID: 5689ad44cdcc
Revises: 6ad03cfd66eb
Create Date: 2026-10-03 21:24:51.906480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5689ad44cdcc'
down_revision: Union[str, Sequence[str], None] = '6ad03cfd66eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('call_id', sa.String(length=80), nullable=True),
    sa.Column('tool_name', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_conversation', 'chat_messages', ['conversation_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_messages_conversation', table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
