"""add users, auth sessions and ownership links

Revision ID: 5d55b70dc28c
Revises: 5689ad44cdcc
Create Date: 2026-10-03 23:45:14.758747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d55b70dc28c'
down_revision: Union[str, Sequence[str], None] = '5689ad44cdcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paypal_payer_id', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('paypal_verified', sa.Boolean(), nullable=False),
    sa.Column('is_dev', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paypal_payer_id')
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.add_column('orders', sa.Column('buyer_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_buyer_user_id'), 'orders', ['buyer_user_id'], unique=False)
    op.create_foreign_key('fk_orders_buyer_user_id_users', 'orders', 'users', ['buyer_user_id'], ['id'])
    op.add_column('sellers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_sellers_user_id', 'sellers', ['user_id'])
    op.create_foreign_key('fk_sellers_user_id_users', 'sellers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sellers_user_id_users', 'sellers', type_='foreignkey')
    op.drop_constraint('uq_sellers_user_id', 'sellers', type_='unique')
    op.drop_column('sellers', 'user_id')
    op.drop_constraint('fk_orders_buyer_user_id_users', 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_buyer_user_id'), table_name='orders')
    op.drop_column('orders', 'buyer_user_id')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
