"""create initial tables

Revision ID: 6ad03cfd66eb
Revises: 
Create Date: 2026-10-03 21:13:59.151256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad03cfd66eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quantity_total', sa.Integer(), nullable=False),
    sa.Column('minimum_units', sa.Integer(), nullable=False),
    sa.Column('max_per_buyer', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('open', 'filled', 'failed', 'cancelled', name='dropstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('max_per_buyer > 0', name='drop_max_per_buyer_positive'),
    sa.CheckConstraint('minimum_units <= quantity_total', name='drop_minimum_within_quantity'),
    sa.CheckConstraint('minimum_units > 0', name='drop_minimum_positive'),
    sa.CheckConstraint('quantity_total > 0', name='drop_quantity_positive'),
    sa.CheckConstraint('unit_price > 0', name='drop_price_positive'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drops_seller_id'), 'drops', ['seller_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drop_id', sa.Integer(), nullable=False),
    sa.Column('buyer_name', sa.String(length=120), nullable=False),
    sa.Column('buyer_email', sa.String(length=254), nullable=False),
    sa.Column('chat_session_id', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('reserved', 'authorized', 'captured', 'voided', 'expired', 'failed', name='orderstatus', native_enum=False, length=20), nullable=False),
    sa.Column('reserved_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paypal_order_id', sa.String(length=64), nullable=True),
    sa.Column('paypal_authorization_id', sa.String(length=64), nullable=True),
    sa.Column('authorization_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='order_amount_positive'),
    sa.CheckConstraint('quantity > 0', name='order_quantity_positive'),
    sa.ForeignKeyConstraint(['drop_id'], ['drops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paypal_authorization_id'),
    sa.UniqueConstraint('paypal_order_id')
    )
    op.create_index(op.f('ix_orders_chat_session_id'), 'orders', ['chat_session_id'], unique=False)
    op.create_index('ix_orders_drop_status', 'orders', ['drop_id', 'status'], unique=False)
    op.create_table('drop_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drop_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drop_id'], ['drops.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drop_events_drop_id'), 'drop_events', ['drop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drop_events_drop_id'), table_name='drop_events')
    op.drop_table('drop_events')
    op.drop_index('ix_orders_drop_status', table_name='orders')
    op.drop_index(op.f('ix_orders_chat_session_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_drops_seller_id'), table_name='drops')
    op.drop_table('drops')
    op.drop_table('sellers')
    # ### end Alembic commands ###
